services:
  mysql-db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    command: ["--max_connections=1000000"]
    restart: "no"
    volumes:
      - db:/var/lib/mysql_data

  lyric-app:
    image: duckervn/lyric-be
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    restart: always
volumes:
  db: